### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by kohtala** [scholzj/docker-qpid-cpp#2]
Hi.

Thanks for your effort on Dockerizing qpid-cpp. This seems good and I have interest in using your work. For that I need to have a license, but can not find any. Apache License 2.0 would seem a good guess, as qpid uses that, but I can not guess. It would be helpful if you specified the license you want to offer. The project [community profile](https://github.com/scholzj/docker-qpid-cpp/community) offers easy license selection.

**Comment by scholzj** [comment]
Valid point. Thanks for raising it. I added the license file to the master branch. Let me know if you need something more.

**Comment by kohtala** [comment]
Thanks. This is fine now.
